name: 🪓 Mutiny TV - Master Unificador VOD de Largo Fluido v1.0

on:
  workflow_dispatch: # Botón manual de PLAY en la web de GitHub para armar el cartucho

permissions:
  contents: write
  actions: write

jobs:
  unificar_maraton:
    runs-on: ubuntu-latest
    steps:
      - name: 🗄️ Clonando el búnker de archivos estáticos
        uses: actions/checkout@v4

      # Setup FFmpeg ultra-rápido en 4 segundos sordos
      - name: ⚙️ Setup FFmpeg Nativo en la Nube
        uses: federicocarboni/setup-ffmpeg@v3

      - name: 🚀 Descarga Satelital y Costura Binaria de Películas (Peso Pluma Original)
        run: |
          # 🪓 [REACTOR DE RELEVOS v3.5 - COPIA DIRECTA ANTI-ENGORDE]
          export TERM=xterm
          
          echo "📡 [MUTINY TV] EMPEZANDO PROCESO DE UNIFICACIÓN CRIPTOGRÁFICA..."
          
          # 1. Chupamos tu playlist unificada del Gist privado
          curl -s "https://gist.githubusercontent.com/jav45dev-ctrl/c02c7fac36fde342f061b733231a5e6d/raw/playlist.txt" | tr -d '\r' | sed '/^$/d' > lista_gist.txt
           
          echo "# Lista de archivos para concat" > inputs_ffmpeg.txt
          contador=1
          
          # 2. Descarga a velocidad satelital en la memoria virtual
          while read -r linea || [ -n "$linea" ]; do
            URL_VIDEO=$(echo "$linea" | awk -F'|' '{print $1}' | tr -d ' ')
            
            if [ -n "$URL_VIDEO" ]; then
              echo "📥 Descargando e inyectando Tramo $contador: $URL_VIDEO"
              curl -L -H "Authorization: token ${{ secrets.TOKEN_B }}" \
                   -H "User-Agent: VLC/3.0.18 LibVLC/3.0.18" \
                   -o "origen_${contador}.mp4" "$URL_VIDEO"
              
              echo "file 'origen_${contador}.mp4'" >> inputs_ffmpeg.txt
              contador=$((contador + 1))
            fi
          done < lista_gist.txt

          echo "🪓 [MUTINY] UNIFICANDO BORDES BINARIOS CON BYPASS DE SAR..."
          
          # 3. LA CRÍA MAESTRA: Usamos el motor concat demuxer con -c copy.
          # Metemos -fflags +genpts+igndts para forzar el re-indexado de las líneas de tiempo cruzadas
          ffmpeg -y -f concat -safe 0 -fflags +genpts+igndts -i inputs_ffmpeg.txt -c copy -fflags +genpts maraton_perfecta.mp4

          echo "✅ Súper-video soldado manteniendo el peso pluma original."
          ls -lh maraton_perfecta.mp4

      # Guardamos el archivo liviano adentro de tu nuevo cofre limpio maraton_soberana
      - name: 📦 Guardando Cartucho en las Releases del Repositorio (Auditoría Libre)
        uses: softprops/action-gh-release@v2
        with:
          files: maraton_perfecta.mp4
          tag_name: maraton_soberana
          name: "🍿 Mutiny TV - Maratones Continuas Masterizadas"
          body: "Esta maratón se unificó por copia directa binaria manteniendo el peso liviano original de chapa. ADN intacto, inmune a baches y libre de congelamientos."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
